update mysql galera

diff --git a/bash/ductn b/bash/ductn
--- a/bash/ductn
+++ b/bash/ductn
@@ -600,21 +600,26 @@ mysql-replicate(){
 }
 
 mysql-galera(){
-    sudo apt install -y --purge --auto-remove software-properties-common
-    sudo apt-key adv --keyserver keyserver.ubuntu.com --recv BC19DDBA
 
-    echo "# Codership Repository (Galera Cluster for MySQL)
-deb https://galeracluster.com/wsrep_8.0.19-26.3-rc/galera-4/ubuntu focal main
-deb https://galeracluster.com/wsrep_8.0.19-26.3-rc/mysql-wsrep-8.0/ubuntu focal main
-" | sudo tee /etc/apt/sources.list.d/galera.list
+    _MYSQL_GALERA="on"
 
-    echo "# Prefer Codership repository
-Package: *
-Pin: origin releases.galeracluster.com
-Pin-Priority: 1001
-" | sudo tee /etc/apt/preferences.d/galera.pref
+    while [ $# -gt 0 ]
+    do
+        case $1 in
+            -i|--install)   _MYSQL_GALERA_TOOGLE="on" ;;
+            --remove)       _MYSQL_GALERA_TOOGLE="off" ;;
+            --host=?*|-h=?*)_MYSQL_GALERA_HOST=${1#*=} ;;
+            --host|-h)      _MYSQL_GALERA_HOST=$2; shift ;;
+            --host=)
+                die 'ERROR: "--host" requires a non-empty option argument.'
+                ;;
+            --) break ;;
+            -?*) printf 'WARN: Unknown option (ignored): %s\n' "$1" >&2 ;;
+            *) break ;;
+        esac
 
-    sudo apt update
+        shift
+    done
 
 }
 
@@ -638,7 +643,6 @@ F_init(){
     --aliases -i
     --httpd --config
 }
-
 
 F_mysql_replicate(){
 
@@ -672,6 +676,46 @@ F_mysql_replicate(){
     $@
 }
 
+F_mysql_galera(){
+
+    --setup(){
+        sudo apt install -y --purge --auto-remove software-properties-common
+        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv BC19DDBA
+
+        echo "# Codership Repository (Galera Cluster for MySQL)
+    deb https://galeracluster.com/wsrep_8.0.19-26.3-rc/galera-4/ubuntu focal main
+    deb https://galeracluster.com/wsrep_8.0.19-26.3-rc/mysql-wsrep-8.0/ubuntu focal main
+    " | sudo tee /etc/apt/sources.list.d/galera.list
+
+        echo "# Prefer Codership repository
+    Package: *
+    Pin: origin releases.galeracluster.com
+    Pin-Priority: 1001
+    " | sudo tee /etc/apt/preferences.d/galera.pref
+
+        sudo apt update
+    }
+
+    --install(){
+
+        cat mysql_galera/mysqld.cnf                | sudo tee /etc/mysql/conf.d/mysqld_cluster.cnf
+        cat mysql_galera/dx$@.mysqld.cnf           | sudo tee -a /etc/mysql/conf.d/mysqld_cluster.cnf
+
+        sudo service mysql restart
+    }
+
+    --remove(){
+        sudo rm -rf /etc/mysql/conf.d/mysqld_cluster.cnf
+        sudo rm -rf /etc/apt/sources.list.d/galera.list
+        sudo rm -rf /etc/apt/preferences.d/galera.pref
+
+        sudo apt update
+        sudo service mysql restart
+    }
+
+    $@
+}
+
 if [[ $_INIT = "on" ]]; then
     # echo "_INIT = $_INIT"
     F_init
@@ -685,5 +729,16 @@ if [[ $_MYSQL_REPLICATE = "on" ]]; then
         F_mysql_replicate --install $_MYSQL_REPLICATE_HOST
     else
         F_mysql_replicate --remove
+    fi
+fi
+
+if [[ $_MYSQL_GALERA = "on" ]]; then
+    # echo "_MYSQL_GALERA = $_MYSQL_GALERA"
+    if [[ $_MYSQL_GALERA_TOOGLE = "on" ]]; then
+        # echo "_MYSQL_GALERA_TOOGLE = $_MYSQL_GALERA_TOOGLE"
+        # echo "_MYSQL_GALERA_HOST = $_MYSQL_GALERA_HOST"
+        F_mysql_galera --install $_MYSQL_GALERA_HOST
+    else
+        F_mysql_galera --remove
     fi
 fi
