update cmd hosts:add

diff --git a/bash/hosts b/bash/hosts
--- a/bash/hosts
+++ b/bash/hosts
@@ -8,12 +8,9 @@ ETC_HOSTS=/etc/hosts
     IP=$1
     HOSTNAME=$2
 
-    if [[ -n "$(grep $HOSTNAME /etc/hosts)" ]]; then
-        echo "Remove $HOSTNAME from $ETC_HOSTS"
-        sudo sed -i".bak" "/$HOSTNAME/d" ${ETC_HOSTS}
-    else
-        echo "$HOSTNAME was not found!"
-    fi
+    sudo sed -i".bak" "/$HOSTNAME/d" ${ETC_HOSTS}
+
+    [[ -n "$(grep $HOSTNAME /etc/hosts)" ]] && echo ">> Hosts removed: $HOSTNAME" || echo "$HOSTNAME was not found!"
 }
 
 --hosts:add() {
@@ -21,17 +18,12 @@ ETC_HOSTS=/etc/hosts
     HOSTNAME=$2
 
     HOSTS_LINE="$IP\t$HOSTNAME"
-    if [[ -n "$(grep $HOSTNAME /etc/hosts)" ]]; then
+    if [[ ! -n $(grep -P "$IP[[:space:]]$HOSTNAME" $ETC_HOSTS) ]]; then
         sudo sed -i".bak" "/$HOSTNAME/d" ${ETC_HOSTS}
+        sudo -- sh -c -e "echo '$HOSTS_LINE' >> /etc/hosts"
     fi
 
-    sudo -- sh -c -e "echo '$HOSTS_LINE' >> /etc/hosts"
-
-    if [[ -n "$(grep $HOSTNAME /etc/hosts)" ]]; then
-        echo ">> Done |$(grep $HOSTNAME /etc/hosts)"
-    else
-        echo "Failed to Add $HOSTNAME, Try again!"
-    fi
+    [[ -n $(grep -P "$IP[[:space:]]$HOSTNAME" $ETC_HOSTS) ]] && echo ">> Hosts added: $(grep $HOSTNAME $ETC_HOSTS)" || echo "Failed to Add $HOSTNAME, Try again!"
 }
 
 --hosts() {
